name: Create Raspios Image

on:
  # schedule:
  #   - cron: 0 0 */14 * *
  push:
    branches:
      - master
    paths:
      - "**"
  pull_request:
    paths:
      - "**"
  workflow_dispatch:

jobs:
  build_image:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Script
        run: sudo ./setup.sh raspberrypi pi raspberry nobackup

      - uses: actions/upload-artifact@v4
        name: Upload Generated Image
        with:
          name: raspios.img.xz
          path: ./raspios.img.xz
          if-no-files-found: error